apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bhxacl1zf-nodejs
  janus-idp.io/tekton: bhxacl1zf-nodejs
  backstage.io/kubernetes-id: bhxacl1zf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bhxacl1zf-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
