apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bhxacl1zf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bhxacl1zf-nodejs 
  name: bhxacl1zf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bhxacl1zf-nodejs 
